// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBotvAd3FgQphhx9wt8GYMFr-yyZZ3Zs5E',
    appId: '1:1060353916446:web:de7ced617543711ef0f80f',
    messagingSenderId: '1060353916446',
    projectId: 'chat-app-1e85e',
    authDomain: 'chat-app-1e85e.firebaseapp.com',
    storageBucket: 'chat-app-1e85e.appspot.com',
    measurementId: 'G-CQNHE21DZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1viksDf4KHiHs-7FkDOex5UzrczwHFDw',
    appId: '1:1060353916446:android:d1a16eefef4ba5b9f0f80f',
    messagingSenderId: '1060353916446',
    projectId: 'chat-app-1e85e',
    storageBucket: 'chat-app-1e85e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9AhISDbfGqLvVMEQ28kocJ52Z8tN3pX4',
    appId: '1:1060353916446:ios:312588494339fd32f0f80f',
    messagingSenderId: '1060353916446',
    projectId: 'chat-app-1e85e',
    storageBucket: 'chat-app-1e85e.appspot.com',
    iosClientId: '1060353916446-2dmhup8u81a6emkjqk50m8detklrj6op.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9AhISDbfGqLvVMEQ28kocJ52Z8tN3pX4',
    appId: '1:1060353916446:ios:312588494339fd32f0f80f',
    messagingSenderId: '1060353916446',
    projectId: 'chat-app-1e85e',
    storageBucket: 'chat-app-1e85e.appspot.com',
    iosClientId: '1060353916446-2dmhup8u81a6emkjqk50m8detklrj6op.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
